-- Migration 057 — vector-store upgrade to Voyage voyage-3-large @ 1024 dims.
--
-- Why:
--   Today `intakes.embedding` is `vector(1536)` populated by voyage-3 (native
--   1024 dim) and zero-padded up to 1536 by lib/intake/embed.ts. The padding
--   is wasteful in storage AND mildly hurts cosine math (zeros dilute the
--   similarity). Voyage's highest-quality model `voyage-3-large` is natively
--   1024 dim — same as voyage-3 — so we can collapse the column to its real
--   native dimension and get a model upgrade at the same time.
--
-- What this migration does:
--   1. NULLs every existing intakes.embedding row. This is intentional and
--      safe: the existing voyage-3 vectors are NOT compatible with the new
--      voyage-3-large model (cosine distances aren't comparable across
--      embedding models), so re-embedding is mandatory regardless. NULLing
--      first lets ALTER COLUMN TYPE proceed without USING-clause gymnastics.
--   2. Alters intakes.embedding to vector(1024).
--   3. Drops + recreates match_intakes() with the new vector(1024) signature.
--   4. Adds a comment recording the model + dim assumption for future readers.
--
-- After this migration:
--   - RAG returns 0 matches (no rows have embeddings) until the backfill
--     script runs. lib/estimate/rag.ts handles null context gracefully —
--     the estimator just runs without past-quote anchoring. No user impact.
--   - Run scripts/reembed-intakes-voyage3-large.mjs to repopulate all
--     intakes.embedding values via voyage-3-large.
--
-- Rollback plan (staging only — would never run on prod):
--   ALTER TABLE intakes ALTER COLUMN embedding TYPE vector(1536);
--   Drop function, recreate with vector(1536) signature.
--   Run scripts/reembed-intakes-voyage3.mjs (if reverted) to repopulate.
--
-- Idempotent: re-running is safe — the NULL pass + ALTER TYPE + function
-- recreate are all idempotent, and the comment is upsert-style.

begin;

-- (1) Wipe existing embeddings so the column type change is unambiguous.
--     The backfill script repopulates these with voyage-3-large vectors.
update intakes set embedding = null where embedding is not null;

-- (2) Collapse the column to its real native dimension.
alter table intakes alter column embedding type vector(1024);

-- (3) Recreate match_intakes() with the new vector(1024) signature.
--     Body is identical to migration 006 (job_type pre-filter retained).
drop function if exists match_intakes(vector, int);
drop function if exists match_intakes(vector, int, text);

create or replace function match_intakes(
  query_embedding vector(1024),
  match_count int default 5,
  job_type_filter text default null
)
returns table (id uuid, scope jsonb, similarity float)
language sql stable as $$
  select id, scope, 1 - (embedding <=> query_embedding) as similarity
  from intakes
  where embedding is not null
    and (job_type_filter is null or job_type = job_type_filter)
  order by embedding <=> query_embedding
  limit match_count;
$$;

-- (4) Record the model + dim assumption on the column for future readers.
comment on column intakes.embedding is
  'Voyage voyage-3-large embedding (1024 native dims). See lib/intake/embed.ts. '
  'Generated by structureIntake() and consumed by match_intakes() / RAG.';

commit;
